<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ############################ PARAMETERS ############################# -->
<xacro:property name="base_link_y" value="1.0"/>
<xacro:property name="wheel_radius" value="0.15"/>
<xacro:property name="wheel_width" value="0.05"/>

<!-- ########################### PHYSICS PROPERTIES ###################### -->
<gazebo reference="base_link">
    <mu1>0.5</mu1>
    <mu2>0.5</mu2>
    <material>Gazebo/FlatBlack</material>
    <kp>1e6</kp>
    <kd>1e3</kd>
</gazebo>

<xacro:macro name="wheel_physics" params="link_name">
    <gazebo reference="${link_name}">
        <mu1>1.5</mu1>  <!-- Higher friction for wheels -->
        <mu2>1.5</mu2>
        <material>Gazebo/Rubber</material>
        <kp>1e6</kp>
        <kd>1e3</kd>
    </gazebo>
</xacro:macro>

<xacro:wheel_physics link_name="left_front_link"/>
<xacro:wheel_physics link_name="left_back_link"/>
<xacro:wheel_physics link_name="right_front_link"/>
<xacro:wheel_physics link_name="right_back_link"/>

<!-- ######################## SENSOR CONFIGURATIONS ###################### -->
<!-- Lidar Configuration -->
<gazebo reference="lidar_link">
    <material>Gazebo/Cobalt</material>
    <sensor type="ray" name="main_lidar">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>40</update_rate>
        <ray>
            <scan>
                <horizontal>
                    <samples>1080</samples>
                    <resolution>0.33</resolution>
                    <min_angle>${-pi}</min_angle>
                    <max_angle>${pi}</max_angle>
                </horizontal>
                <vertical>
                    <samples>16</samples>
                    <resolution>0.01</resolution>
                    <min_angle>-0.1</min_angle>
                    <max_angle>0.1</max_angle>
                </vertical>
            </scan>
            <range>
                <min>0.25</min>
                <max>30.0</max>
                <resolution>0.03</resolution>
            </range>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.0075</stddev>
            </noise>
        </ray>
        <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
            <topic_name>scan</topic_name>
            <frame_name>lidar_link</frame_name>
            <radiation_type>infrared</radiation_type>
        </plugin>
    </sensor>
</gazebo>

<!-- IMU Configuration -->
<gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>400</update_rate>
        <imu>
            <noise>
                <type>gaussian</type>
                <rate>
                    <mean>0.0</mean>
                    <stddev>0.00017</stddev>
                    <bias_mean>0.0001</bias_mean>
                    <bias_stddev>0.0001</bias_stddev>
                </rate>
                <accel>
                    <mean>0.0</mean>
                    <stddev>0.0028</stddev>
                    <bias_mean>0.1</bias_mean>
                    <bias_stddev>0.001</bias_stddev>
                </accel>
            </noise>
        </imu>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
            <topic_name>imu/data</topic_name>
            <frame_name>imu_link</frame_name>
            <initial_orientation_as_reference>false</initial_orientation_as_reference>
        </plugin>
    </sensor>
</gazebo>

<!-- GPS Configuration -->
<gazebo reference="gps_link">
    <sensor name="gps_sensor" type="gps">
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <plugin name="gps_plugin" filename="libgazebo_ros_gps_sensor.so">
            <topic_name>gps/fix</topic_name>
            <frame_name>gps_link</frame_name>
            <reference_latitude>49.899720</reference_latitude>
            <reference_longitude>8.900277</reference_longitude>
            <reference_altitude>105.0</reference_altitude>
            <velocity_noise>0.05</velocity_noise>
        </plugin>
    </sensor>
</gazebo>

<!-- Camera Configuration -->
<gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
        <camera>
            <horizontal_fov>1.5708</horizontal_fov>  <!-- 90 degrees -->
            <image>
                <width>1280</width>
                <height>720</height>
                <format>RGB8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>100.0</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>
        </camera>
        <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
            <camera_name>main_camera</camera_name>
            <frame_name>camera_link_optical</frame_name>
            <hack_baseline>0.07</hack_baseline>
        </plugin>
    </sensor>
</gazebo>

<!-- ###################### DRIVE CONTROLLER PLUGIN ###################### -->
<gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
        <command_topic>cmd_vel</command_topic>
        <odometry_topic>odom</odometry_topic>
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_link</robot_base_frame>
        
        <wheel_separation>${base_link_y * 0.9}</wheel_separation>
        <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
        <wheel_acceleration>2.5</wheel_acceleration>
        <wheel_torque>35</wheel_torque>
        
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>false</publish_wheel_tf>
        
        <ros>
            <namespace>${ns}</namespace>
        </ros>
        
        <wheel_joints>
            left_front_wheel_joint
            right_front_wheel_joint
            left_back_wheel_joint
            right_back_wheel_joint
        </wheel_joints>
    </plugin>
</gazebo>

<!-- ########################### SENSOR LINKS ########################### -->
<gazebo reference="gps_link">
    <material>Gazebo/BrightYellow</material>
    <sensor name="gps_sensor" type="gps">...</sensor>
</gazebo>

<gazebo reference="imu_link">
    <material>Gazebo/EmissiveGreen</material>
</gazebo>

</robot>